import {useEffect,useState} from 'react';
import {Icon} from './ui';
import './business.css';

const services=[
 {number:'01',title:'Customer communication',text:'Respond to enquiries, send appointment reminders, and keep customers informed with consistent, timely messages.'},
 {number:'02',title:'Data & documents',text:'Reduce repeated typing, organise information, and extract useful details from documents for your team to review.'},
 {number:'03',title:'Internal operations',text:'Make routine reminders, approval requests, task assignments, and employee administration easier to manage.'},
 {number:'04',title:'Business reporting',text:'Bring information together and prepare regular summaries so managers spend less time collecting updates.'},
];
const examples=[
 {category:'SALES & CUSTOMER SERVICE',title:'Give every enquiry a timely response.',business:'For a real estate agency',task:'A team checks website enquiries, copies contact details, and sends the same introductory message throughout the day.',automation:'New enquiry details can be recorded automatically, an acknowledgement prepared, and the relevant sales representative notified.',benefit:'Less copying and fewer enquiries left waiting.'},
 {category:'FINANCE & ADMINISTRATION',title:'Spend less time entering invoice details.',business:'For a trading company',task:'Accounts staff read supplier invoices and manually enter amounts, dates, and reference numbers into a spreadsheet.',automation:'Document information can be extracted into a draft record, with missing or unusual details flagged for a person to check.',benefit:'Less data entry, with review before approval.'},
 {category:'CUSTOMER COMMUNICATION',title:'Keep appointments on everyone’s radar.',business:'For a professional services firm',task:'Staff call or message customers individually to confirm appointments and remind them what to bring.',automation:'Confirmation messages and reminders can be prepared from the appointment schedule, using the customer’s preferred channel where supported.',benefit:'More consistent communication and less repetitive messaging.'},
 {category:'INVENTORY & OPERATIONS',title:'Know when stock needs attention.',business:'For a retail or distribution business',task:'An employee checks stock sheets regularly and emails colleagues when quantities are running low.',automation:'Stock levels can be checked against agreed limits and a summary sent to the purchasing team for review.',benefit:'Earlier visibility without repeatedly checking spreadsheets.'},
 {category:'PEOPLE & ADMINISTRATION',title:'Make new-joiner preparation more consistent.',business:'For a growing team',task:'HR repeatedly sends document requests and reminds different colleagues to prepare equipment, access, and induction information.',automation:'A new-joiner record can generate a standard checklist and scheduled reminders for the people responsible.',benefit:'Clearer responsibilities and fewer missed administrative tasks.'},
 {category:'MANAGEMENT & REPORTING',title:'Bring daily updates into one clear summary.',business:'For a business with multiple departments',task:'Managers gather separate sales, service, and operations updates before putting together a daily report.',automation:'Information from agreed sources can be collected into a summary, with AI helping draft the commentary for review.',benefit:'Less time compiling updates and more time acting on them.'},
];
const questions=[
 ['What does business automation mean?','It means using software to handle repetitive activities, such as recording enquiries, preparing reminders, or collecting information for a report. The aim is to reduce routine administration.'],
 ['Where does AI help?','AI can assist with reading documents, categorising requests, summarising information, and drafting messages. People should review outputs wherever accuracy, judgement, or approval matters.'],
 ['Can this work with tools we already use?','Email, spreadsheets, customer databases, and other business software may be suitable. What is possible depends on the tools, their available connections, and the access your business authorises.'],
 ['Do we need to automate everything at once?','No. A practical starting point is one frequent, well-defined task. Agree what a good result looks like, test it with the team, and expand only when it is useful.'],
];
function Brand(){return <span className="business-brand"><span className="business-brand-symbol"><Icon name="Integrations" size={21}/></span>AutoFlow<span className="brand-dot">.</span></span>}

export function BusinessSite(){
 const [theme,setTheme]=useState(()=>localStorage.getItem('af-theme')||'light');
 const [menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('af-theme',theme)},[theme]);
 useEffect(()=>{const resetOldRoute=()=>{if(location.hash.startsWith('#/')){history.replaceState(null,'',location.pathname+location.search+'#home');window.scrollTo(0,0)}};resetOldRoute();window.addEventListener('hashchange',resetOldRoute);return()=>window.removeEventListener('hashchange',resetOldRoute)},[]);
 const links=[['Home','home'],['Services','services'],['Examples','examples'],['Our approach','approach']];
 return <div className="business-site">
 <header className="business-header"><div className="business-nav shell"><a href="#home" aria-label="AutoFlow home"><Brand/></a><nav aria-label="Main navigation" className={menu?'is-open':''}>{links.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="business-nav-actions"><button className="business-icon-button" aria-label="Toggle dark mode" onClick={()=>setTheme(theme==='light'?'dark':'light')}><Icon name={theme==='light'?'Moon':'Sun'} size={19}/></button><a className="business-button compact" href="#examples">Explore examples <Icon name="ArrowUpRight" size={16}/></a><button className="business-icon-button business-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?'X':'Menu'}/></button></div></div></header>
 <main>
 <section className="business-hero" id="home"><div className="shell hero-layout"><div className="hero-copy"><p className="business-kicker">BUSINESS AUTOMATION · DUBAI</p><h1>Less repetitive work.<br/><span>More room for business.</span></h1><p className="business-intro">Automate everyday business activities—from customer enquiries and document handling to internal reminders and reporting.</p><p className="hero-support">Practical uses of AI and automation that give your team more time for customers, decisions, and growth.</p><a className="business-button" href="#examples">See practical examples <Icon name="ArrowRight" size={17}/></a></div><aside className="hero-editorial"><div className="editorial-heading"><span>THE EVERYDAY OPPORTUNITY</span><Icon name="Briefcase" size={21}/></div><h2>Small tasks.<br/>A significant part<br/>of your day.</h2><p>Start with the work your team repeats most often.</p><div className="editorial-line"><span>01</span><strong>Following up with customers</strong></div><div className="editorial-line"><span>02</span><strong>Entering the same information</strong></div><div className="editorial-line"><span>03</span><strong>Collecting daily updates</strong></div><div className="editorial-note">More consistency. Less routine administration.</div></aside></div></section>
 <section className="business-section shell" id="services"><div className="business-section-heading"><div><p className="business-kicker">WHAT CAN BE AUTOMATED</p><h2>Everyday activities.<br/>Across your business.</h2></div><p>Focus on the repeatable work that takes up time. Keep your team involved where judgement, relationships, and approvals matter.</p></div><div className="service-text-grid">{services.map(s=><article key={s.number}><span className="service-number">{s.number}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
 <section className="business-examples business-section" id="examples"><div className="shell"><div className="business-section-heading"><div><p className="business-kicker">PRACTICAL EXAMPLES</p><h2>What this could look like<br/>in your business.</h2></div><p>A few familiar situations, explained simply. These are illustrative examples; the right solution depends on your processes and tools.</p></div><div className="business-example-grid">{examples.map((e,i)=><article className="business-example" key={e.title}><div className="example-category"><span>{e.category}</span><span>{String(i+1).padStart(2,'0')}</span></div><h3>{e.title}</h3><p className="example-business">{e.business}</p><div className="example-description"><h4>The everyday task</h4><p>{e.task}</p><h4>With automation</h4><p>{e.automation}</p></div><p className="example-benefit"><Icon name="Check" size={17}/>{e.benefit}</p></article>)}</div></div></section>
 <section className="business-perspective"><div className="shell perspective-layout"><div><p className="business-kicker">AI WITH A CLEAR PURPOSE</p><h2>Useful assistance.<br/>Human judgement.</h2></div><div><p>AI can help make sense of an incoming message, extract details from a document, or prepare a first draft. Automation can take care of the routine administration around it.</p><p>Your people remain responsible for important decisions, customer relationships, and final approvals.</p></div></div></section>
 <section className="business-section shell" id="approach"><div className="business-section-heading"><div><p className="business-kicker">A PRACTICAL APPROACH</p><h2>Start with one task.<br/>Make a useful difference.</h2></div><p>A clear business need is the best starting point. Technology should fit the way your team works.</p></div><div className="approach-text-grid">{[['01','Understand the activity','Identify a task that happens often, who handles it, and where time is lost.'],['02','Define the right assistance','Decide what can be automated, what information is needed, and where a person should review the result.'],['03','Test and refine','Try a small, clearly defined use case. Check accuracy, usefulness, and time saved before expanding.']].map(([n,title,text])=><article key={n}><span className="service-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="business-questions business-section"><div className="shell questions-layout"><div><p className="business-kicker">A LITTLE MORE CONTEXT</p><h2>Common questions.</h2></div><div>{questions.map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></section>
 <section className="business-close shell"><div><p className="business-kicker">MAKE TIME FOR WHAT MATTERS</p><h2>Which everyday task<br/>would you simplify first?</h2><p>Start with your most frequent manual activity and consider what a better way of working could look like.</p></div><a className="business-button" href="#examples">Revisit the examples <Icon name="ArrowUpRight" size={17}/></a></section>
 </main>
 <footer className="business-footer"><div className="shell"><div className="footer-main"><a href="#home" aria-label="AutoFlow home"><Brand/></a><p>Automation for everyday business activities.</p><nav aria-label="Footer navigation"><a href="#services">Services</a><a href="#examples">Examples</a><a href="#approach">Our approach</a></nav></div><div className="footer-small"><span>© {new Date().getFullYear()} AutoFlow</span><span>Dubai · Business automation</span></div></div></footer>
 </div>
}
