import {
  ArrowRight,
  ArrowUpRight,
  Check,
  ChartNoAxesCombined,
  Files,
  Globe2,
  Layers3,
  Menu,
  MessageSquare,
  Moon,
  Settings2,
  Sun,
  Users,
  X,
  ShoppingBag,
  Megaphone,
  Activity,
  Plus,
  Minus,
  Play,
  Pause,
} from "lucide-react";
const icons = {
  ArrowRight,
  ArrowUpRight,
  Check,
  Analytics: ChartNoAxesCombined,
  Documents: Files,
  Globe: Globe2,
  Layers: Layers3,
  Menu,
  Messages: MessageSquare,
  Moon,
  Operations: Settings2,
  Sun,
  People: Users,
  X,
  Commerce: ShoppingBag,
  Marketing: Megaphone,
  Trading: Activity,
  Plus,
  Minus,
  Play,
  Pause,
};
type IconProps = { name: keyof typeof icons; size?: number };
export function Icon({ name, size = 20 }: IconProps) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={1.6} aria-hidden="true" />;
}
