import {createContext,useContext,useId} from 'react';
import {ArrowRight,ArrowUpRight,Workflow,Zap,Users,Headphones,Search,ChartNoAxesCombined,Megaphone,Receipt,BriefcaseBusiness,Check,ChevronDown,ChevronRight,Plus,Play,Pause,Settings,LayoutDashboard,Activity,Blocks,Bot,Bell,Sun,Moon,Menu,X,Mail,FileText,Database,GitBranch,GripVertical,Trash2,Copy,Save,ShieldCheck,LockKeyhole,KeyRound,Globe,BookOpen,ExternalLink,CheckCircle2,AlertCircle,LoaderCircle,LogOut,CreditCard,MoreHorizontal,ArrowLeft,MoveUp,MoveDown,Linkedin,Github,Youtube,Send,Download,RotateCcw} from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import {siGmail,siGoogledrive,siGooglesheets,siHubspot,siMongodb,siNotion,siPostgresql,siShopify,siStripe,siWhatsapp,siDiscord} from 'simple-icons';
const icons={ArrowRight,ArrowUpRight,Workflow,Zap,Users,Headphones,Search,Chart:ChartNoAxesCombined,Megaphone,Receipt,Briefcase:BriefcaseBusiness,Check,ChevronDown,ChevronRight,Plus,Play,Pause,Settings,Overview:LayoutDashboard,Activity,Integrations:Blocks,Bot,Bell,Sun,Moon,Menu,X,Mail,FileText,Database,GitBranch,Grip:GripVertical,Trash:Trash2,Copy,Save,Shield:ShieldCheck,Lock:LockKeyhole,Key:KeyRound,Globe,Book:BookOpen,ExternalLink,CheckCircle:CheckCircle2,Alert:AlertCircle,Loader:LoaderCircle,LogOut,Billing:CreditCard,More:MoreHorizontal,ArrowLeft,MoveUp,MoveDown,Linkedin,Github,Youtube,Send,Download,Reset:RotateCcw};
export function Icon({name,size=20,...props}:{name:string;size?:number;className?:string}){const C=icons[name as keyof typeof icons]||Workflow;return <C size={size} strokeWidth={1.7} aria-hidden="true" {...props}/>}
export function Logo({compact=false}:{compact?:boolean}){return <span className="logo"><span className="logo-mark"><Workflow size={24} strokeWidth={2}/></span>{!compact&&<>AutoFlow<span className="logo-period">.</span></>}</span>}
const brandIcons:Record<string,{path:string}>={Gmail:siGmail,'Google Drive':siGoogledrive,'Google Sheets':siGooglesheets,HubSpot:siHubspot,MongoDB:siMongodb,Notion:siNotion,PostgreSQL:siPostgresql,Shopify:siShopify,Stripe:siStripe,WhatsApp:siWhatsapp,Discord:siDiscord};
export function ToolLogo({name,mark,color}:{name:string;mark:string;color:string}){const brand=brandIcons[name];return <span className="tool-logo" style={{color,background:color+'12'}} aria-label={name}>{brand?<svg viewBox="0 0 24 24" width="23" height="23" fill="currentColor" aria-hidden="true"><path d={brand.path}/></svg>:name==='Webhooks'?<Workflow size={23}/>:name==='Microsoft Teams'?<Users size={23}/>:mark}</span>}
export function Badge({children,color='purple'}:{children:React.ReactNode;color?:string}){return <span className={'badge '+color}>{children}</span>}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal"><div className="modal-head"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-button" aria-label="Close dialog"><Icon name="X"/></Dialog.Close></div><Dialog.Description className="modal-description">{description||'Explore this feature in the AutoFlow product preview.'}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export const UIContext=createContext<{toast:(message:string)=>void;theme:string;toggleTheme:()=>void;openInfo:(title:string,body:string)=>void}>({toast:()=>{},theme:'light',toggleTheme:()=>{},openInfo:()=>{}});
export const useUI=()=>useContext(UIContext);
export function Chart({variant='line',period='30'}:{variant?:'line'|'bars';period?:string}){
 const id=useId().replace(/:/g,'');
 const values=period==='7'?[143,171,159,178,165,190,184]:[24,33,27,49,42,58,52,71,65,78,70,94,84,105,99,117,108,130,122,143,138,156,143,171,159,178,165,190];
 const dx=700/(values.length-1),bw=700/values.length;
 return <div className="chart"><svg viewBox="0 0 700 220" role="img" aria-label={`Sample ${variant==='line'?'automation activity':'completed tasks'} over ${period} days`}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7866ed" stopOpacity=".23"/><stop offset="100%" stopColor="#7866ed" stopOpacity="0"/></linearGradient></defs>{[30,75,120,165,210].map(y=><line key={y} x1="0" x2="700" y1={y} y2={y} stroke="currentColor" opacity=".08"/>)}{variant==='line'?<><path d={`M0,220 ${values.map((v,i)=>`L${i*dx},${215-v}`).join(' ')} L700,220 L0,220Z`} fill={`url(#${id})`}/><polyline points={values.map((v,i)=>`${i*dx},${215-v}`).join(' ')} fill="none" stroke="#7866ed" strokeWidth="3" strokeLinejoin="round"/></>:values.map((v,i)=><rect key={i} x={i*bw+bw*.18} y={220-v} width={bw*.6} height={v} rx="3" fill={i%3===0?'#a99bf7':'#7866ed'}><title>{`Day ${i+1}: ${v} sample tasks`}</title></rect>)}</svg><div className="chart-labels">{(period==='7'?['Sep 22','Sep 24','Sep 26','Sep 28']:['Sep 01','Sep 07','Sep 14','Sep 21','Sep 28']).map(x=><span key={x}>{x}</span>)}</div></div>
}

